namespace: default

nmi:
  forceNamespaced: true
  prometheusPort: 9090
  image:
    repo: mcr.microsoft.com/k8s/aad-pod-identity/nmi
    tag: 1.5.5

mic:
  forceNamespaced: true
  prometheusPort: 9090
  image:
    repo: mcr.microsoft.com/k8s/aad-pod-identity/mic
    tag: 1.5.5
