{{ range $index, $e := until (int .Values.replicaCount ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" $ }}-{{ $index }}
  labels:
{{ include "standard.labels" $  | indent 4 }}
spec:
  type: {{ $.Values.service.type }}
{{- if $.Values.geth.use_static_ips }}
  loadBalancerIP: {{ index $.Values.geth.public_ips $index -}}
{{- end }}
  ports:
    - port: 30303
      targetPort: discovery-tcp
      protocol: TCP
      name: discovery-tcp
    - port: 8545
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "common.fullname" $ }}-{{ $index }}
---
{{ end }}
