apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ template "name" . }}-identity-binding
spec:
  AzureIdentity: {{ template "name" . }}-identity
  Selector: {{ template "name" . }}-identity-binding
