apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{ include "oracle-client-component-label" . | indent 4 }}
spec:
  clusterIP: None
  selector:
{{ include "oracle-client-component-label" . | indent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{ include "oracle-client-component-label" . | indent 4 }}
spec:
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  serviceName: oracle
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
{{ include "oracle-client-component-label" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels" . | indent 8 }}
{{ include "oracle-client-component-label" . | indent 8 }}
        aadpodidbinding: {{ template "azure-identity-binding-name" . }}
    spec:
      containers:
      - name: oracle-client
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command:
          - bash
          - "-c"
          - |
            [[ $REPLICA_NAME =~ -([0-9]+)$ ]] || exit 1
            RID=${BASH_REMATCH[1]}
            ORACLE_ACCOUNT_ADDRESSES={{ join "," .Values.oracle.addresses }}
            # Needed by the oracle client
            export ORACLE_ACCOUNT_ADDRESS=`echo -n $ORACLE_ACCOUNT_ADDRESSES | cut -d ',' -f $((RID + 1))`
            node /celo-oracle/lib/run_app.js
        env:
        - name: REPLICA_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CELO_NODE
          value: {{ .Values.oracle.web3ProviderUrl }}
        - name: AZURE_KEY_VAULT
          value: {{ .Values.azure.keyVault.name }}
