environmentName: test
replicas: 2
image:
  repository: oracletest.azurecr.io/test/oracle
  tag: hsmtest

oracle:
  addresses: 0x0000000000000000000000000000000000000000,0x0000000000000000000000000000000000000001
  web3ProviderUrl: https://alfajoresstaging-forno.celo-testnet.org
azure:
  identity:
    id: defaultId
    clientId: defaultClientId
  keyVault:
    name: defaultKeyVaultName
